-- ===== INSERT CATEGORIES SAFELY =====
INSERT INTO CATEGORIES (CATEGORY_NAME)
SELECT 'Furniture' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIES WHERE CATEGORY_NAME = 'Furniture');

INSERT INTO CATEGORIES (CATEGORY_NAME)
SELECT 'Lighting' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIES WHERE CATEGORY_NAME = 'Lighting');

INSERT INTO CATEGORIES (CATEGORY_NAME)
SELECT 'Kitchen' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIES WHERE CATEGORY_NAME = 'Kitchen');

INSERT INTO CATEGORIES (CATEGORY_NAME)
SELECT 'Decor' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIES WHERE CATEGORY_NAME = 'Decor');

-- ===== INSERT WAREHOUSES SAFELY =====
INSERT INTO WAREHOUSES (NAME, LOCATION)
SELECT 'Main Warehouse', '123 Industrial Park' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM WAREHOUSES WHERE NAME = 'Main Warehouse');

INSERT INTO WAREHOUSES (NAME, LOCATION)
SELECT 'City Hub', '456 Downtown Ave' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM WAREHOUSES WHERE NAME = 'City Hub');

-- ===== INSERT USERS SAFELY =====
INSERT INTO USERS (EMAIL, PASSWORD, NAME, ROLE)
SELECT 'admin@ikea.com', 'admin123', 'Admin User', 'ADMIN' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'admin@ikea.com');

INSERT INTO USERS (EMAIL, PASSWORD, NAME, ROLE)
SELECT 'user@example.com', 'user123', 'John Doe', 'CUSTOMER' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'user@example.com');

-- ===== INSERT DISCOUNTS_CODES =====
INSERT INTO DISCOUNT_CODES (CODE, DISCOUNT_PERCENTAGE, EXPIRY_DATE, USAGE_LIMIT, IS_ACTIVE)
SELECT 'WELCOME10', 10, SYSDATE + 60, 100, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DISCOUNT_CODES WHERE CODE = 'WELCOME10');

-- ===== INSERT PRODUCTS SAFELY =====
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_PRICE, CATEGORY_ID)
SELECT 'EKTORP Sofa', 399.00, CATEGORY_ID 
FROM CATEGORIES 
WHERE CATEGORY_NAME = 'Furniture'
  AND NOT EXISTS (
        SELECT 1 FROM PRODUCTS WHERE PRODUCT_NAME = 'EKTORP Sofa'
  );

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_PRICE, CATEGORY_ID)
SELECT 'BILLY Bookcase', 69.00, CATEGORY_ID 
FROM CATEGORIES 
WHERE CATEGORY_NAME = 'Furniture'
  AND NOT EXISTS (
        SELECT 1 FROM PRODUCTS WHERE PRODUCT_NAME = 'BILLY Bookcase'
  );

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_PRICE, CATEGORY_ID)
SELECT 'HEKTAR Floor Lamp', 59.99, CATEGORY_ID
FROM CATEGORIES 
WHERE CATEGORY_NAME = 'Lighting'
  AND NOT EXISTS (
        SELECT 1 FROM PRODUCTS WHERE PRODUCT_NAME = 'HEKTAR Floor Lamp'
  );

-- ===== INSERT INVENTORY SAFELY =====
INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, STOCK_QUANTITY)
SELECT p.PRODUCT_ID, w.WAREHOUSE_ID, 50
FROM PRODUCTS p
JOIN WAREHOUSES w ON w.NAME = 'Main Warehouse'
WHERE p.PRODUCT_NAME = 'EKTORP Sofa'
AND NOT EXISTS (
    SELECT 1 FROM INVENTORY 
    WHERE PRODUCT_ID = p.PRODUCT_ID 
      AND WAREHOUSE_ID = w.WAREHOUSE_ID
);

INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, STOCK_QUANTITY)
SELECT p.PRODUCT_ID, w.WAREHOUSE_ID, 100
FROM PRODUCTS p
JOIN WAREHOUSES w ON w.NAME = 'Main Warehouse'
WHERE p.PRODUCT_NAME = 'BILLY Bookcase'
AND NOT EXISTS (
    SELECT 1 FROM INVENTORY 
    WHERE PRODUCT_ID = p.PRODUCT_ID 
      AND WAREHOUSE_ID = w.WAREHOUSE_ID
);

COMMIT;
